// File is used to define the constants mostly used between reducers and actions

export const WALLET_CONNECT_REQUEST = "WALLET_CONNECT_REQUEST";
export const WALLET_CONNECT_SUCCESS = "WALLET_CONNECT_SUCCESS";
export const WALLET_CONNECT_ERROR = "WALLET_CONNECT_ERROR";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";