// File is used to define the constants mostly used between reducers and actions

export const WALLET_CONNECT_REQUEST = "WALLET_CONNECT_REQUEST";
export const WALLET_CONNECT_SUCCESS = "WALLET_CONNECT_SUCCESS";
export const WALLET_CONNECT_ERROR = "WALLET_CONNECT_ERROR";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";


export const CATEGORY_CU_REQUEST = "CATEGORY_CU_REQUEST";
export const CATEGORY_CU_SUCCESS = "CATEGORY_CU_SUCCESS";
export const CATEGORY_CU_ERROR = "CATEGORY_CU_ERROR";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR";

export const CATEGORY_SINGLE_REQUEST = "CATEGORY_SINGLE_REQUEST";
export const CATEGORY_SINGLE_SUCCESS = "CATEGORY_SINGLE_SUCCESS";
export const CATEGORY_SINGLE_ERROR = "CATEGORY_SINGLE_ERROR";


export const SUBCATEGORY_LIST_REQUEST = "SUBCATEGORY_LIST_REQUEST";
export const SUBCATEGORY_LIST_SUCCESS = "SUBCATEGORY_LIST_SUCCESS";
export const SUBCATEGORY_LIST_ERROR = "SUBCATEGORY_LIST_ERROR";


export const SUBCATEGORY_CU_REQUEST = "SUBCATEGORY_CU_REQUEST";
export const SUBCATEGORY_CU_SUCCESS = "SUBCATEGORY_CU_SUCCESS";
export const SUBCATEGORY_CU_ERROR = "SUBCATEGORY_CU_ERROR";

export const SUBCATEGORY_SINGLE_REQUEST = "SUBCATEGORY_SINGLE_REQUEST";
export const SUBCATEGORY_SINGLE_SUCCESS = "SUBCATEGORY_SINGLE_SUCCESS";
export const SUBCATEGORY_SINGLE_ERROR = "SUBCATEGORY_SINGLE_ERROR";

export const SUBCATEGORY_DELETE_REQUEST = "SUBCATEGORY_DELETE_REQUEST";
export const SUBCATEGORY_DELETE_SUCCESS = "SUBCATEGORY_DELETE_SUCCESS";
export const SUBCATEGORY_DELETE_ERROR = "SUBCATEGORY_DELETE_ERROR";